{
    "name": "EIGR Gestión de Obras",
    "summary": "Gestión academica del ciclo de obras de EIGR Contratistas",
    "version": "19.0.6.0.0",
    "category": "Services/Project",
    "author": "Proyecto academico EIGR",
    "license": "LGPL-3",
    "depends": ["base", "mail", "contacts", "web", "uom"],
    "data": [
        "security/eigr_security.xml",
        "security/ir.model.access.csv",
        "data/construction_sequence.xml",
        "data/construction_demo_data.xml",
        "views/construction_budget_views.xml",
        "views/construction_valuation_views.xml",
        "views/construction_requirement_views.xml",
        "views/construction_closure_views.xml",
        "views/construction_project_views.xml",
        "views/construction_dashboard_views.xml",
        "views/construction_worksheet_views.xml",
        "report/construction_reports.xml",
        "views/construction_menus.xml",
    ],
    "application": True,
    "installable": True,
}
